"""add worker profile cognitive assessment

Revision ID: 6b5011550384
Revises: 9c43f6725cfc
Create Date: 2026-04-13 12:41:26.204614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b5011550384'
down_revision: Union[str, None] = '9c43f6725cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cognitive_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reaction_time_ms', sa.Float(), nullable=True),
    sa.Column('memory_score', sa.Integer(), nullable=True),
    sa.Column('attention_score', sa.Integer(), nullable=True),
    sa.Column('spatial_score', sa.Integer(), nullable=True),
    sa.Column('knowledge_score', sa.Integer(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Enum('FIT', 'SUPERVISION_REQUIRED', 'UNFIT', name='cognitiveresult'), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_assessments_user_id'), 'cognitive_assessments', ['user_id'], unique=False)
    op.create_table('worker_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodgroup'), nullable=True),
    sa.Column('dominant_hand', sa.Enum('LEFT', 'RIGHT', 'AMBIDEXTROUS', name='dominanthand'), nullable=True),
    sa.Column('identification_mark', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('major_illness', sa.Text(), nullable=True),
    sa.Column('disability', sa.Text(), nullable=True),
    sa.Column('known_allergies', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('last_medical_checkup', sa.Date(), nullable=True),
    sa.Column('fitness_status', sa.Enum('CLEARED', 'RESTRICTED', 'UNFIT', 'PENDING', name='fitnessstatus'), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('zone_assignment', sa.String(length=100), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_profiles_user_id'), 'worker_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_profiles_user_id'), table_name='worker_profiles')
    op.drop_table('worker_profiles')
    op.drop_index(op.f('ix_cognitive_assessments_user_id'), table_name='cognitive_assessments')
    op.drop_table('cognitive_assessments')
    # ### end Alembic commands ###
